disabled_rules:
  - trailing_newline
  - trailing_whitespace
  - line_length
  - colon
  - comma
  - type_name
  - valid_docs 

opt_in_rules:
  - variable_name
  - empty_count
  - force_cast
  - force_try
  - leading_whitespace
  - function_body_length
  - function_parameter_count
  - legacy_constant
  - operator_whitespace
  - return_arrow_whitespace
  - todo
  - nesting

included: # paths to include during linting. `--path` is ignored if present.
  - PicassoHouse

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
